stages:
 # - build
 # - test
 - docker-build
 - deploy

# build:
#   rules:
#     - if: '$CI_COMMIT_REF_NAME == "master"'
#   stage: build
#   image: node
#   before_script:
#     - curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?chat_id=-1002085454126&text=%F0%9F%9A%80"
#     - curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%9A%A7%20start%20$CI_JOB_NAME%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%3Ci%3Estart%20at%20$CI_COMMIT_TIMESTAMP%3C%2Fi%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
#   script:
#     - echo "Start building App"
#     - echo "GitLab CI/CD | Print all environment variables"
#     - env
#     - echo "$ENV_PROD" > .env
#     - ls -a
#     - cat .env
#     - yarn
#     - yarn build
#     - echo "Build successfully!"
#   after_script:
#     - >
#       if [ $CI_JOB_STATUS == 'success' ]; then
#         curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%E2%9C%85%20$CI_JOB_NAME%20success%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A1%20of%203"
#       else
#         curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%99%88%20$CI_JOB_NAME%20failed%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
#       fi
#   artifacts:
#     expire_in: 1 hour
#     paths:
#       - build
#       - node_modules/

# test:
#   stage: test
#   image: node
#   script:
#     - echo "Testing App"
#     - CI=true npm run test
#     - echo "Test successfully!"
#   after_script:
#     - >
#       if [ $CI_JOB_STATUS == 'success' ]; then
#         curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%E2%9C%85%20$CI_JOB_NAME%20success%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A2%20of%204"
#       else
#         curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%99%88%20$CI_JOB_NAME%20failed%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
#       fi

docker-build:
 rules:
  - if: '$CI_COMMIT_REF_NAME == "master"'
 stage: docker-build
 image: docker:20.10.22
 services:
  - name: docker:19.03.8-dind
 before_script:
  - 'apk --no-cache add curl'
  - curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?chat_id=-1002085454126&text=%F0%9F%9A%80"
  - curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%9A%A7%20start%20$CI_JOB_NAME%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%3Ci%3Estart%20at%20$CI_COMMIT_TIMESTAMP%3C%2Fi%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 script:
  - echo "GitLab CI/CD | Print all environment variables"
  - env
  - echo "$ENV_PROD" > .env
  - cat .env
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker push "$CI_REGISTRY_IMAGE"
  - echo "Registry image:" $CI_REGISTRY_IMAGE
 after_script:
  - >
   if [ $CI_JOB_STATUS == 'success' ]; then
     curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%E2%9C%85%20$CI_JOB_NAME%20success%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A1%20of%202"
   else
     curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%99%88%20$CI_JOB_NAME%20failed%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
   fi


deploy:
 rules:
  - if: '$CI_COMMIT_REF_NAME == "master"'
 stage: deploy
 image: kroniak/ssh-client
 before_script:
  - echo "deploying app"
  - 'apk --no-cache add curl'
 script:
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
  - chmod 400 key.pem
  - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker image prune --force --filter='dangling=true'"
  - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker pull $CI_REGISTRY_IMAGE"
  - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker stop $CI_PROJECT_NAME-container || true && docker rm $CI_PROJECT_NAME-container || true"
  - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker run -p $HOST_PORT:$CONTAINER_PORT -d --name $CI_PROJECT_NAME-container $CI_REGISTRY_IMAGE"
 after_script:
  - >
   if [ $CI_JOB_STATUS == 'success' ]; then
     curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%E2%9C%85%20$CI_JOB_NAME%20success%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A2%20of%202"
     curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?chat_id=-1002085454126&text=%F0%9F%A5%B3"
   else
     curl --location --request GET "https://api.telegram.org/bot5499231928:AAHRsHtbGpS80fu7sonnTCIo2CUh32hNb-k/sendMessage?parse_mode=HTML&chat_id=-1002085454126&text=%F0%9F%99%88%20$CI_JOB_NAME%20failed%20%3A%20%3Cb%3E$CI_PROJECT_NAME%3C%2Fb%3E%0A%0A%F0%9F%91%B7%E2%80%8D%E2%99%82%EF%B8%8F%20$GITLAB_USER_LOGIN%0A%0Apipeline%20%3A%20%23$CI_PIPELINE_IID%0A%0A%F0%9F%9A%80%20%3Ca%20href%3D%22$CI_PIPELINE_URL%22%3Ego%20to%20pipeline%3C%2Fa%3E%0A%0A"
   fi

